#ifndef CMAKECONFIG_H
#define CMAKECONFIG_H

// the configured options and settings
#define PROGRAM_NAME "@PROGRAM_NAME@"

#define PROGRAM_VERSION_MAJOR @PROGRAM_VERSION_MAJOR@
#define PROGRAM_VERSION_MINOR @PROGRAM_VERSION_MINOR@
#define PROGRAM_VERSION_CHANGE @PROGRAM_VERSION_CHANGE@

#endif