# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_AdvantagesWidget.ui'
#
# Created: Tue Jan 10 18:28:00 2012
#      by: pyside-uic 0.2.11 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AdvantagesWidget(object):
	def setupUi(self, AdvantagesWidget):
		AdvantagesWidget.setObjectName("AdvantagesWidget")
		AdvantagesWidget.resize(189, 403)
		self.verticalLayout = QtGui.QVBoxLayout(AdvantagesWidget)
		self.verticalLayout.setObjectName("verticalLayout")
		self.gridLayout = QtGui.QGridLayout()
		self.gridLayout.setObjectName("gridLayout")
		self.label = QtGui.QLabel(AdvantagesWidget)
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.horizontalLayout_6 = QtGui.QHBoxLayout()
		self.horizontalLayout_6.setSpacing(0)
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.label_size = QtGui.QLabel(AdvantagesWidget)
		self.label_size.setObjectName("label_size")
		self.horizontalLayout_6.addWidget(self.label_size)
		self.label_sizeShapes = QtGui.QLabel(AdvantagesWidget)
		self.label_sizeShapes.setObjectName("label_sizeShapes")
		self.horizontalLayout_6.addWidget(self.label_sizeShapes)
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_6.addItem(spacerItem)
		self.gridLayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
		self.label_2 = QtGui.QLabel(AdvantagesWidget)
		self.label_2.setObjectName("label_2")
		self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
		self.horizontalLayout_5 = QtGui.QHBoxLayout()
		self.horizontalLayout_5.setSpacing(0)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.label_initiative = QtGui.QLabel(AdvantagesWidget)
		self.label_initiative.setObjectName("label_initiative")
		self.horizontalLayout_5.addWidget(self.label_initiative)
		self.label_initiativeShapes = QtGui.QLabel(AdvantagesWidget)
		self.label_initiativeShapes.setObjectName("label_initiativeShapes")
		self.horizontalLayout_5.addWidget(self.label_initiativeShapes)
		spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem1)
		self.gridLayout.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
		self.label_3 = QtGui.QLabel(AdvantagesWidget)
		self.label_3.setObjectName("label_3")
		self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
		self.horizontalLayout_4 = QtGui.QHBoxLayout()
		self.horizontalLayout_4.setSpacing(0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.label_speed = QtGui.QLabel(AdvantagesWidget)
		self.label_speed.setObjectName("label_speed")
		self.horizontalLayout_4.addWidget(self.label_speed)
		self.label_speedShapes = QtGui.QLabel(AdvantagesWidget)
		self.label_speedShapes.setObjectName("label_speedShapes")
		self.horizontalLayout_4.addWidget(self.label_speedShapes)
		spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem2)
		self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
		self.label_4 = QtGui.QLabel(AdvantagesWidget)
		self.label_4.setObjectName("label_4")
		self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
		self.horizontalLayout_3 = QtGui.QHBoxLayout()
		self.horizontalLayout_3.setSpacing(0)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.label_defense = QtGui.QLabel(AdvantagesWidget)
		self.label_defense.setObjectName("label_defense")
		self.horizontalLayout_3.addWidget(self.label_defense)
		spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem3)
		self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
		self.label_5 = QtGui.QLabel(AdvantagesWidget)
		self.label_5.setObjectName("label_5")
		self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
		self.horizontalLayout_2 = QtGui.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.spinBox_armorGeneral = QtGui.QSpinBox(AdvantagesWidget)
		self.spinBox_armorGeneral.setMaximum(9)
		self.spinBox_armorGeneral.setObjectName("spinBox_armorGeneral")
		self.horizontalLayout_2.addWidget(self.spinBox_armorGeneral)
		self.label_6 = QtGui.QLabel(AdvantagesWidget)
		self.label_6.setObjectName("label_6")
		self.horizontalLayout_2.addWidget(self.label_6)
		self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
		self.horizontalLayout = QtGui.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.spinBox_armorFirearms = QtGui.QSpinBox(AdvantagesWidget)
		self.spinBox_armorFirearms.setMaximum(9)
		self.spinBox_armorFirearms.setObjectName("spinBox_armorFirearms")
		self.horizontalLayout.addWidget(self.spinBox_armorFirearms)
		self.label_7 = QtGui.QLabel(AdvantagesWidget)
		self.label_7.setObjectName("label_7")
		self.horizontalLayout.addWidget(self.label_7)
		self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
		self.verticalLayout.addLayout(self.gridLayout)
		self.label_8 = QtGui.QLabel(AdvantagesWidget)
		self.label_8.setAlignment(QtCore.Qt.AlignCenter)
		self.label_8.setObjectName("label_8")
		self.verticalLayout.addWidget(self.label_8)
		self.horizontalLayout_7 = QtGui.QHBoxLayout()
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_7.addItem(spacerItem4)
		self.dots_health = TraitDots(AdvantagesWidget)
		self.dots_health.setObjectName("dots_health")
		self.horizontalLayout_7.addWidget(self.dots_health)
		self.label_healthShapes = QtGui.QLabel(AdvantagesWidget)
		self.label_healthShapes.setObjectName("label_healthShapes")
		self.horizontalLayout_7.addWidget(self.label_healthShapes)
		spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_7.addItem(spacerItem5)
		self.verticalLayout.addLayout(self.horizontalLayout_7)
		spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		self.verticalLayout.addItem(spacerItem6)
		self.label_9 = QtGui.QLabel(AdvantagesWidget)
		self.label_9.setAlignment(QtCore.Qt.AlignCenter)
		self.label_9.setObjectName("label_9")
		self.verticalLayout.addWidget(self.label_9)
		self.horizontalLayout_9 = QtGui.QHBoxLayout()
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_9.addItem(spacerItem7)
		self.dots_willpower = TraitDots(AdvantagesWidget)
		self.dots_willpower.setObjectName("dots_willpower")
		self.horizontalLayout_9.addWidget(self.dots_willpower)
		spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_9.addItem(spacerItem8)
		self.verticalLayout.addLayout(self.horizontalLayout_9)
		spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		self.verticalLayout.addItem(spacerItem9)
		self.label_powerstat = QtGui.QLabel(AdvantagesWidget)
		self.label_powerstat.setAlignment(QtCore.Qt.AlignCenter)
		self.label_powerstat.setObjectName("label_powerstat")
		self.verticalLayout.addWidget(self.label_powerstat)
		self.horizontalLayout_10 = QtGui.QHBoxLayout()
		self.horizontalLayout_10.setObjectName("horizontalLayout_10")
		spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_10.addItem(spacerItem10)
		self.dots_powerstat = TraitDots(AdvantagesWidget)
		self.dots_powerstat.setObjectName("dots_powerstat")
		self.horizontalLayout_10.addWidget(self.dots_powerstat)
		spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_10.addItem(spacerItem11)
		self.verticalLayout.addLayout(self.horizontalLayout_10)
		spacerItem12 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		self.verticalLayout.addItem(spacerItem12)
		self.label_fuel = QtGui.QLabel(AdvantagesWidget)
		self.label_fuel.setAlignment(QtCore.Qt.AlignCenter)
		self.label_fuel.setObjectName("label_fuel")
		self.verticalLayout.addWidget(self.label_fuel)
		self.horizontalLayout_8 = QtGui.QHBoxLayout()
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.squares_fuel = Squares(AdvantagesWidget)
		self.squares_fuel.setObjectName("squares_fuel")
		self.horizontalLayout_8.addWidget(self.squares_fuel)
		spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_8.addItem(spacerItem13)
		self.label_fuelPerTurn = QtGui.QLabel(AdvantagesWidget)
		self.label_fuelPerTurn.setObjectName("label_fuelPerTurn")
		self.horizontalLayout_8.addWidget(self.label_fuelPerTurn)
		self.verticalLayout.addLayout(self.horizontalLayout_8)
		spacerItem14 = QtGui.QSpacerItem(20, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout.addItem(spacerItem14)

		self.retranslateUi(AdvantagesWidget)
		QtCore.QMetaObject.connectSlotsByName(AdvantagesWidget)

	def retranslateUi(self, AdvantagesWidget):
		AdvantagesWidget.setWindowTitle(QtGui.QApplication.translate("AdvantagesWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("AdvantagesWidget", "Size:", None, QtGui.QApplication.UnicodeUTF8))
		self.label_size.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_sizeShapes.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("AdvantagesWidget", "Initiative:", None, QtGui.QApplication.UnicodeUTF8))
		self.label_initiative.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_initiativeShapes.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_3.setText(QtGui.QApplication.translate("AdvantagesWidget", "Speed:", None, QtGui.QApplication.UnicodeUTF8))
		self.label_speed.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_speedShapes.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_4.setText(QtGui.QApplication.translate("AdvantagesWidget", "Defense:", None, QtGui.QApplication.UnicodeUTF8))
		self.label_defense.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_5.setText(QtGui.QApplication.translate("AdvantagesWidget", "Armor:", None, QtGui.QApplication.UnicodeUTF8))
		self.label_6.setText(QtGui.QApplication.translate("AdvantagesWidget", "General", None, QtGui.QApplication.UnicodeUTF8))
		self.label_7.setText(QtGui.QApplication.translate("AdvantagesWidget", "Firearms", None, QtGui.QApplication.UnicodeUTF8))
		self.label_8.setText(QtGui.QApplication.translate("AdvantagesWidget", "Health", None, QtGui.QApplication.UnicodeUTF8))
		self.label_healthShapes.setText(QtGui.QApplication.translate("AdvantagesWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_9.setText(QtGui.QApplication.translate("AdvantagesWidget", "Willpower", None, QtGui.QApplication.UnicodeUTF8))
		self.label_powerstat.setText(QtGui.QApplication.translate("AdvantagesWidget", "Powerstat", None, QtGui.QApplication.UnicodeUTF8))
		self.label_fuel.setText(QtGui.QApplication.translate("AdvantagesWidget", "Fuel", None, QtGui.QApplication.UnicodeUTF8))
		self.label_fuelPerTurn.setText(QtGui.QApplication.translate("AdvantagesWidget", "perTurn", None, QtGui.QApplication.UnicodeUTF8))

from src.Widgets.Components.TraitDots import TraitDots
from src.Widgets.Components.Squares import Squares
